### PR TITLE
Port CMS fix 15966

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue Port CMS fix 15966

### Summary of Changes
Port CMS fix 15966 - Fixing InputFilter adding byte offsets to character offset

### Testing Instructions
Should pass filtering this included content
[content.txt](https://github.com/joomla-framework/filter/files/998096/content.txt)

unit tests based on this and other content provided by Joomla users and tests created by @PhilETaylor are included

### Documentation Changes Required
none

### CODE REVIEW

**Comment by photodude** [comment]
@ggppdk This ports your JFilterInput fix to the framework

**Comment by PhilETaylor** [comment]
> unit tests based on this content provided by @PhilETaylor are included

These are based on real-world content Joomla users provided saying that it failed in 3.7.0 - after the patch these tests dont stall - I can vouch for the value of the actual content as a test, except for the fact that it will prevent regression to a stalling of the tests.

**Comment by photodude** [comment]
@mbabker @wilsonge @rdeutz, do we need to get this fix merged in the framework, tag a new release, and bring the updated package into the CMS for the 3.7.1 release?

**Comment by wilsonge** [comment]
Version tagged

**Comment by photodude** [comment]
Thanks @wilsonge

**Pull request merged**
