### PR TITLE
remove the xhtml filter on single tags

### PR DESCRIPTION
**Pull request by brianteeman**
This addresses various bug reports in the cms where html is being rewritten as xhtml

### CODE REVIEW

**Comment by brianteeman** [comment]
The tests need updating and I am not 100% confident with that

**Comment by Hackwar** [comment]
The tests are perfectly fine. Your code will result in every opening tag being replaced with a self-closing tag, leaving the closing tag behind. This fix unfortunately is not correct.

**Comment by Hackwar** [comment]
I reviewed this further and this really is not going to be the solution for this. In theory, we could implement a list of allowed self-closing tags and check against that, but I very much dislike that, since it will shortly become another source of bugs when that list is extended in the future. I do understand that HTML5 allows for these non-closing tags, but at the same time, I don't think we will be able to get this correct in the longterm. So I'd rather return XHTML than non-complying HTML5. To change this behavior, we would need a completely different approach, which is why I'm going to close this one. Also please note that I would consider this a breaking change, meaning that this can not go into 2.0-dev.

**Comment by brianteeman** [comment]
you have misunderstood the issue. the pr might well be wrong but it doesnt change the fact that joomla is taking perfectly valid html and converting it invalid html. 

pleas reopen all the issue that were closed by this pr. I cant

**Comment by Hackwar** [comment]
I'd love to do that, but there is no issue linked to this PR and from a quick glance, I also can't find any closed issues in the CMS repo related to this.

**Pull request closed without merging**
