### PR TITLE
Fix Array to String conversion notices in clean()

### PR DESCRIPTION
**Pull request by photodude**
* Adds basic first level processing of array's of numbers
  * Fixes Array to String conversion notices in clean() for number cases
* Replaces `decode()` with `html_entity_decode()`
* Updates pcre patterns for numbers
  * Fixes floats case to properly handle exponent type floats rather than just decimal floats
* Adds new general cases to test and verify the array of numbers functionality
* Code style: fixes missing comma at end of array lists.

### CODE REVIEW

**Comment by photodude** [comment]
@mbabker This PR is finally ready for merge consideration.

**Comment by RickR2H** [comment]
@photodude To test it I downloaded the Joomla staging. For some reason I'm not able to reproduce the error again. It looks like the issue is somehow fixed. Was the PR already merged?

Thanks for the great work and effort by the way...!

**Comment by photodude** [comment]
@RickR2H this PR in the framework has not been merged, and has not been added to the CMS. The CMS Joomla staging branch would eventually get this patch after it's merged. Testing the CMA Joomla staging branch right now wouldn't test this patch.

If you want to test against your original reproduction steps, I could set up a fork of the CMS with these changes. 

There are a number of reasons why your issue might not have came up, including differences in global error reporting settings (likely need to test with developer level error reporting). It's also possible that something may have changed in the tags component that could mask  (or eliminate) the case that was causing your array to string notices. 

In any case this PR should make a good improvement to the filtering in the framework and the CMS with improved guarding against cases of array to string notices caused by filtering of multidimensional array's of numbers.

**Comment by mbabker** [comment]
Do you have any test cases that would've triggered this?

**Comment by photodude** [comment]
@mbabker this was originally created in response to https://github.com/joomla/joomla-cms/pull/7405

Outside of the issue listed there (and the replication steps identified), I don't currently know if another  test case in the CMS that would have need filtering of multidimensional array's of numbers. but this also insures that no array of numbers has array to string conversions. 

Should I create some test cases to add to the unit tests to insure this catches the filtering of multidimensional array's of numbers?

**Comment by RickR2H** [comment]
@photodude I think it's a good idea to make a test case. That way we honor the way Joomla uses PR's and tests to accept code ;) Unfortunately this is a bit outside my comfort zone. It's no problem fort me to do the test.

**Comment by photodude** [comment]
@RickR2H I've created a forked branch of the CMS to test the filtering with.
https://github.com/photodude/joomla-cms/tree/Filter-tests

I'll see about adding the test cases later this week.

**Comment by mbabker** [comment]
If that condition in the CMS is what's triggering it, usually what I end up doing is catching a var_dump of the relevant data then reassembling that in a test method.

**Comment by photodude** [comment]
@mbabker I was unable to replicate this issue with the provided steps. I did take a shot at a possible scenario and have added a basic level of filtering of arrays to the unit tests to verify the additional methods in the functions. As it currently stands it does not deal with multidimensional arrays, just basic arrays of numbers. 

This also eliminates the `decode()` method and uses the newer `html_entity_decode`

This should still be a nice improvement over the exiting code and should guard against future cases of Array to string conversion notices with numbers.

**Comment by mbabker** [comment]
I'll look things over this weekend.

**Comment by mbabker** [comment]
Using this test script, I can validate the issue and fix:

```php
<?php

// Require Composer to be loaded
$autoloader = __DIR__ . '/vendor/autoload.php';

if (!is_readable($autoloader))
{
	echo 'Composer is not set up, please run "composer install".';

	exit(1);
}

require_once $autoloader;

$inputFilter = new \Joomla\Filter\InputFilter;

// Clean a single string value to integer
var_dump($inputFilter->clean('42', 'int')); //int(42)

// Clean a single string value with alphanumeric characters to integer
var_dump($inputFilter->clean('abc123', 'int')); //int(123)

// Clean an array of string values to integer
var_dump($inputFilter->clean(array('42', '123'), 'int'));
// Pre-patch: Notice: Array to string conversion in src/InputFilter.php on line 177
// Post-patch: array(2) { [0] => int(42) [1] => int(123) }

// Clean an array of string values with alphanumeric characters to integer
var_dump($inputFilter->clean(array('42', 'abc123'), 'int'));
// Pre-patch: Notice: Array to string conversion in src/InputFilter.php on line 177
// Post-patch: array(2) { [0] => int(42) [1] => int(0) }
```

The issue basically boils down to certain cases expecting only a single value to clean and not knowing how to deal with an array of values to clean.  So this is a very valid and much needed fix/improvement.

That said though, my final test case (`array('42', 'abc123')`) is inconsistent with the existing behavior.  IMO with that fixed the integer cases are fixed (and presumably the same will be needed for the unsigned integer and float/double cases).

**Comment by photodude** [comment]
unsigned integer and float/double cases are include in this patch. 

I'm not sure why there is an inconsistency with the test case `array('42', 'abc123')` the results should be `array('42', '123')` and not the resulting `array(2) { [0] => int(42) [1] => int(0) }`

I'll see about digging into why that case is failing.

**Comment by mbabker** [comment]
The format is what `var_dump()` spits out (I just consolidated it into one line), but it roughly equates to `array(42, 0)`

**Comment by photodude** [comment]
@mbabker This should be ready and should be more consistent with existing behavior

I have also fixed the floats case to properly handle exponent type floats rather than just decimal floats

**Comment by photodude** [comment]
@mbabker This PR will definitely pass all the tests now (the new tests are also included).

Once this is PR is merged, I believe the changes will need to be back-ported to the CMS since it looks like the CMS uses a modified version of the input filter.

**Comment by mbabker** [comment]
Seems fine now.  Squashed the commits and merged in.

I did back out the changes from `$this->decode()` to `html_entity_decode()`.  `$this->decode()` is already deprecated and just calls `html_entity_decode()` anyway, but it is a potential B/C break to make the change in the off chance anyone actually subclassed the `InputFilter` class and implemented a custom decode method.

**Comment by photodude** [comment]
Thanks, glad to see this merged. 

I can understand, the back out of the the changes from `$this->decode()` to `html_entity_decode()`, maybe that's an item to change in 2.0

**Comment by antonioribeiro** [comment]
Are you planning to tag a version anytime soon? 
This "Array to string conversion" error is annoying... :)

**Pull request closed without merging**
