### PR TITLE
Allow <br> instead of <br />

### PR DESCRIPTION
**Pull request by PhilETaylor**
https://github.com/joomla/joomla-cms/issues/34135

### CODE REVIEW

**Comment by brianteeman** [comment]
I see your stalker is here

**Comment by PhilETaylor** [comment]
Well unless he has a better solution that he wishes to share - I'll just ignore him

**Comment by wilsonge** [comment]
I think we've broken ability to validate the XHTML compliant br tags (which you'd have if you upgraded from J3) judging by the tests failing after my commit. May also just be misinterpreting the tests

**Comment by PhilETaylor** [comment]
its a filter, not a validator :)

**Comment by nibra** [comment]
Since both <br> and <br/> are valid (AFAIK), the filter should not change one form into the other.

**Comment by PhilETaylor** [comment]
> Since both  and  are valid (AFAIK), the filter should not change one form into the other.

Unfortunately it does. 

Provide it with a `<br>` and it will convert it to `<br />` and Joomla 4 took the decision not to use that type but to use `<br>` - see joomla/joomla-cms#34135 for test case

**Comment by nibra** [comment]
But if we make changes to the filter, the right result should come out, and not the other "almost right", shouldn't it?

**Comment by brianteeman** [comment]
They are not both valid html. It is only in xhtml that the /> should be used https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

**Comment by PhilETaylor** [comment]
Im sorry Im not following you @nibra 

I think what you are saying is that this PR is not good enough, although it meets the needs of the Joomla project. 

I think you are saying that the filter should allow, and not convert, the input of `<br> and <br />` and should output the untouched version of `<br> and <br />` that was input.

**Comment by nibra** [comment]
@PhilETaylor Yes, that was what I was trying to say, but I stay corrected by @brianteeman. The method is used in a roundabout way by cleanHTML() (and not cleanXHTML()), which is why `<br>` is probably perfectly OK. Only the comment in line 518 of InputFilter.php would have to be adapted (HTML instead of XHTML).

**Pull request closed without merging**
